language: python

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

sudo: false

env:
  PYTHONPATH: lib:test
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- tox
- tox -e flake8
- pylint lib/AddonSignals.py test/
#- kodi-addon-checker . --branch=krypton
#- kodi-addon-checker . --branch=leia
- coverage run -m unittest discover

after_success:
- codecov
